//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankLoansDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class LoanAgreement
    {
        public int PK_AgreementId { get; set; }
        public Nullable<int> FK_Bank_RegNumber { get; set; }
        public Nullable<int> FK_ClientId { get; set; }
        public string AgreementNumber { get; set; }
        public float Interest { get; set; }
        public int Months { get; set; }
        public decimal LoanAmount { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public System.DateTime ContractDate { get; set; }
        public Nullable<bool> IsRepaid { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Client Client { get; set; }
    }
}
