//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankLoansDataModel
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.Banks = new ObservableCollection<Bank>();
        }
    
        public int PK_OfferId { get; set; }
        public float Interest { get; set; }
        public decimal MinLoanAmount { get; set; }
        public decimal MaxLoanAmount { get; set; }
        public int MaxOfMonths { get; set; }
        public Nullable<int> ActiveLoansNumber { get; set; }
        public Nullable<int> MinSeniority { get; set; }
        public Nullable<int> MinAge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Bank> Banks { get; set; }
    }
}
